# Generated by Django 3.1.7 on 2021-04-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='users',
            name='reppassword',
            field=models.CharField(default='', max_length=50, verbose_name='Повтор Пароля'),
            preserve_default=False,
        ),
    ]
